# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
        empty_content: 204
        view_response_listener: force
