framework:
    secret: '%env(APP_SECRET)%'

    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/config/serialization/']

    templating:
        engines: ['twig']
