framework:
    secret: '%env(APP_SECRET)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/config/serialization/']

    templating:
        engines: ['twig']
