liip_imagine:
    driver: gd
    filter_sets:
        square_sm:
            quality: 75
            filters:
                thumbnail:
                    allow_upscale: true
                    mode: inset
                    size: [128, 128]
        square_md:
            quality: 80
            filters:
                thumbnail:
                    allow_upscale: true
                    mode: inset
                    size: [256, 256]
        square_lg:
            quality: 80
            filters:
                thumbnail:
                    allow_upscale: true
                    mode: inset
                    size: [512, 512]
