nelmio_api_doc:
    documentation:
        info:
            title: TEA Rest API
            version: '1.0-alpha.0'
            description: TEA Rest API docs
        securityDefinitions:
            ApiToken:
                type: apiKey
                name: X-AUTH-TOKEN
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc) # Accepts routes under /api except /api/doc
