twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    exception_controller: App\Component\Common\Controller\ExceptionController::showAction
    strict_variables: '%kernel.debug%'
