controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_auth:
    resource: ../../src/Component/Auth/Controller/
    type: annotation

controllers_calendar:
    resource: ../../src/Component/Calendar/Controller/
    type: annotation

controllers_common:
    resource: ../../src/Component/Common/Controller/
    type: annotation

controllers_io:
    resource: ../../src/Component/IO/Controller/
    type: annotation

