App\Entity\Guardian:
    attributes:
        birthDate:
            groups: ["guardian-common", "guardian-full"]
        email:
            groups: ["guardian-full"]
        id:
            groups: ["guardian-id", "guardian-common", "guardian-full"]
        name:
            groups: ["guardian-common", "guardian-full"]
        surname:
            groups: ["guardian-common", "guardian-full"]
