App\Entity\Image:
    attributes:
        id:
            groups: ["image-id", "image-common", "image-full"]
        path:
            groups: ["image-common", "image-full"]
        text:
            groups: ["image-common", "image-full"]
        type:
            groups: ["image-full"]
